# Generated by Django 2.1 on 2018-11-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PleniApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='videourl',
            field=models.CharField(default='youtube.com', max_length=200),
        ),
    ]
