# Generated by Django 2.1 on 2018-12-01 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PleniApp', '0003_auto_20181128_1156'),
    ]

    operations = [
        migrations.RenameModel('Thread', 'Lecture')
    ]
