# Generated by Django 2.1 on 2018-12-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PleniApp', '0004_auto_20181130_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_type_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='unit_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='videourl',
            field=models.CharField(max_length=200),
        ),
    ]
