# Generated by Django 2.1 on 2018-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PleniApp', '0005_auto_20181130_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_index_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='navlinkid',
            field=models.CharField(default='navlink_', max_length=20),
        ),
    ]
