# Generated by Django 2.1 on 2018-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PleniApp', '0007_auto_20181204_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(default='tgbNymZ7vqY'),
        ),
    ]
