# Generated by Django 2.1 on 2018-12-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PleniApp', '0008_auto_20181205_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='videourl',
            field=models.CharField(default='tgbNymZ7vqY', max_length=200),
        ),
    ]
