# Generated by Django 2.1 on 2018-12-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PleniApp', '0009_auto_20181205_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
